force-app/main/default/objects/Order/fields/REF__c.field-meta.xml
<CustomField>
    <fullName>REF__c</fullName>
    <formula>SBQQ__Quote__r.REF__c</formula>
    <label>REF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/Pre_Defined_Quote_Notes__c.object-meta.xml
<CustomObject>
    <label>Pre Defined Quote Note</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Pre Defined Quote Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Defined Quote Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TECH SUPPORT</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT QUOTED STATEMENT</fullName>
            </value>
            <value>
                <fullName>RENTAL PERIOD</fullName>
            </value>
            <value>
                <fullName>POWERLENS/AGM NOTE</fullName>
            </value>
            <value>
                <fullName>AGM INSTALLATION GUIDE NOTE</fullName>
            </value>
            <value>
                <fullName>FREIGHT QUOTES</fullName>
            </value>
            <value>
                <fullName>EFT PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/NoteDetails__c.field-meta.xml
<CustomField>
    <fullName>NoteDetails__c</fullName>
    <label>Note Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/Predefined_Qts__c.object-meta.xml
<CustomObject>
    <label>Predefined+Qts</label>
    <nameField>
        <label>Predefined+Qts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined+Qts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Predefined_Qts__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Pre_Defined_Quote_Note__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Pre_Defined_Quote_Note__c.field-meta.xml
<CustomField>
    <fullName>Pre_Defined_Quote_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pre Defined Quote Note</label>
    <referenceTo>Pre_Defined_Quote_Notes__c</referenceTo>
    <relationshipLabel>Predefined+Qts</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Predefined Notes (QUOTE)</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Quote_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Order_Number__c</fullName>
    <formula>Pre_Defined_Quote_Note__r.Order_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/REF__c.field-meta.xml
<CustomField>
    <fullName>REF__c</fullName>
    <label>REF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PaymentTerms__c</fullName>
    <description>Terms that govern payment of the items in this quote.</description>
    <inlineHelpText>Terms that govern payment of the items in this quote.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due on receipt</fullName>
            </value>
            <value>
                <fullName>NET 15</fullName>
            </value>
            <value>
                <fullName>NET 30</fullName>
                <default>true</default>
                <label>NET 30</label>
            </value>
            <value>
                <fullName>NET 45</fullName>
            </value>
            <value>
                <fullName>NET 60</fullName>
            </value>
            <value>
                <fullName>NET 90</fullName>
            </value>
            <value>
                <fullName>CONVERSION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundamentalQuoteTemplateHeader.cls
public class FundamentalQuoteTemplateHeader {
    public String quoteId { get; set; }
    public String templateId { get; set; }
    public String notesHeader { get; set; }
    public String discountHeader { get; set; }
    public List<String> noteList { get; set; }
    public SBQQ__Quote__c quote { get; set; }
    public List<String> orderedNoteDescriptions { get; set; }

    public FundamentalQuoteTemplateHeader(ApexPages.StandardController controller) {

        quoteId = ApexPages.currentPage().getParameters().get('qid');
        templateId = ApexPages.currentPage().getParameters().get('tid');
        noteList = new List<String>{''};
        discountHeader = '';

        if (String.isBlank(quoteId) || String.isBlank(templateId)) { return; }
        // Get the quote
        quote = [
            SELECT Id, SBQQ__Notes__c, SBQQ__AdditionalDiscountAmount__c, 
            SBQQ__PaymentTerms__c, REF__c, SBQQ__PrimaryContact__r.Name
            FROM SBQQ__Quote__c 
            WHERE Id = :quoteId 
            LIMIT 1
        ];

        setupTemplateDependentFields();

        // Get and sort all notes by Category__c, then Quote_Order_Number__c
        List<Predefined_Qts__c> predefinedQts = [
            SELECT Id, Pre_Defined_Quote_Note__c,
                Pre_Defined_Quote_Note__r.Name,
                Pre_Defined_Quote_Note__r.NoteDetails__c,
                Category__c,
                Quote_Order_Number__c
            FROM Predefined_Qts__c
            WHERE Quote__c = :quoteId
            ORDER BY Category__c ASC, Quote_Order_Number__c ASC
        ];
        // initialize noteList with '' just in case there are no notes
        if (quote.SBQQ__Notes__c != null) {
            String cleanedNotes = quote.SBQQ__Notes__c.replace('\r', '&#160;');
            noteList = cleanedNotes.split('\n');
        }
        
        // Flatten into List<String>
        orderedNoteDescriptions = new List<String>();
        for (Predefined_Qts__c note : predefinedQts) {
            if (note.Pre_Defined_Quote_Note__r != null &&
                String.isNotBlank(note.Pre_Defined_Quote_Note__r.NoteDetails__c)) {
                orderedNoteDescriptions.add(note.Pre_Defined_Quote_Note__r.NoteDetails__c);
            }
        }
    }

    private void setupTemplateDependentFields() {
        SBQQ__QuoteTemplate__c templateRec = null;
        List<SBQQ__QuoteTemplate__c> results = [
            SELECT Id, Name 
            FROM SBQQ__QuoteTemplate__c 
            WHERE Id = :templateId 
            LIMIT 1
        ];

        if (!results.isEmpty()) {
            templateRec = results[0];
        }
        
        if (templateRec == null) {
            System.debug('No template found for the given templateId: ' + templateId);
            return;
        }
        // SBQQ__AdditionalDiscountAmount__c
        notesHeader = 'CONTRACT NOTES:';
        

        if (templateRec.Name.contains('Quote')) {
            notesHeader = 'QUOTATION NOTES:';
        }
        if(quote.SBQQ__AdditionalDiscountAmount__c != null && quote.SBQQ__AdditionalDiscountAmount__c > 0) {
            
            if(!templateRec.Name.contains('BOL')) {
                discountHeader = 'DISCOUNT GIVEN: $CAD ' + quote.SBQQ__AdditionalDiscountAmount__c;
            }

        }
        


    }
}