force-app/main/default/objects/Pre_Defined_Quote_Notes__c/Pre_Defined_Quote_Notes__c.object-meta.xml
<CustomObject>
    <label>Pre Defined Quote Note</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Pre Defined Quote Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Defined Quote Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TECH SUPPORT</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT QUOTED STATEMENT</fullName>
            </value>
            <value>
                <fullName>RENTAL PERIOD</fullName>
            </value>
            <value>
                <fullName>POWERLENS/AGM NOTE</fullName>
            </value>
            <value>
                <fullName>AGM INSTALLATION GUIDE NOTE</fullName>
            </value>
            <value>
                <fullName>FREIGHT QUOTES</fullName>
            </value>
            <value>
                <fullName>EFT PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/NoteDetails__c.field-meta.xml
<CustomField>
    <fullName>NoteDetails__c</fullName>
    <label>Note Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/Predefined_Qts__c.object-meta.xml
<CustomObject>
    <label>Predefined+Qts</label>
    <nameField>
        <label>Predefined+Qts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined+Qts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Predefined_Qts__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Pre_Defined_Quote_Note__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Pre_Defined_Quote_Note__c.field-meta.xml
<CustomField>
    <fullName>Pre_Defined_Quote_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pre Defined Quote Note</label>
    <referenceTo>Pre_Defined_Quote_Notes__c</referenceTo>
    <relationshipLabel>Predefined+Qts</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Predefined Notes (QUOTE)</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Fundamental_Quotes.recordType-meta.xml
<RecordType>
    <fullName>Fundamental_Quotes</fullName>
    <active>true</active>
    <description>Fundamental Quotes</description>
    <label>Fundamental Quotes</label>
</RecordType>

force-app/main/default/classes/QuoteTriggerTest.cls
@isTest
public with sharing class QuoteTriggerTest {

    public static final String quoteFundamentalRecTypeId = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Fundamental_Quotes').getRecordTypeId();

    @TestSetup
    static void makeData(){
        List<Pre_Defined_Quote_Notes__c> predefinedNotes = new List<Pre_Defined_Quote_Notes__c>();
        Pre_Defined_Quote_Notes__c techNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'TECH SUPPORT',
            NoteDetails__c = 'Technical Notes'
        );
        predefinedNotes.add(techNotes);
        Pre_defined_Quote_Notes__c equipmentNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'EQUIPMENT QUOTED STATEMENT',
            NoteDetails__c = 'Equipment Notes'
        );
        predefinedNotes.add(equipmentNotes);
        insert predefinedNotes;
    }
    @isTest
    static void onAfterInsertTest() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();
        Account account = TestDataFactory.createFundamentalTestAccount();
        System.runAs(adminUser) {
            SBQQ__Quote__c quote = new SBQQ__Quote__c(
                RecordTypeId = quoteFundamentalRecTypeId,
                SBQQ__Account__c = account.Id
            );
            insert quote;

            List<Predefined_Qts__c> notes = [SELECT Id, Pre_Defined_Quote_Note__c FROM Predefined_Qts__c WHERE Quote__c = :quote.Id];
            System.assertEquals(2, notes.size(), 'Two predefined notes should be created.');
        }
        

    }

}