force-app/main/default/objects/Pre_Defined_Quote_Notes__c/Pre_Defined_Quote_Notes__c.object-meta.xml
<CustomObject>
    <label>Pre Defined Quote Note</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Pre Defined Quote Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Defined Quote Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TECH SUPPORT</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT QUOTED STATEMENT</fullName>
            </value>
            <value>
                <fullName>RENTAL PERIOD</fullName>
            </value>
            <value>
                <fullName>POWERLENS/AGM NOTE</fullName>
            </value>
            <value>
                <fullName>AGM INSTALLATION GUIDE NOTE</fullName>
            </value>
            <value>
                <fullName>FREIGHT QUOTES</fullName>
            </value>
            <value>
                <fullName>EFT PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/NoteDetails__c.field-meta.xml
<CustomField>
    <fullName>NoteDetails__c</fullName>
    <label>Note Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Fundamental_Quotes.recordType-meta.xml
<RecordType>
    <fullName>Fundamental_Quotes</fullName>
    <active>true</active>
    <description>Fundamental Quotes</description>
    <label>Fundamental Quotes</label>
</RecordType>

force-app/main/default/classes/FundamentalQuoteTemplateHeaderTest.cls
@isTest
public with sharing class FundamentalQuoteTemplateHeaderTest {

    public static final String quoteFundamentalRecTypeId = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Fundamental_Quotes').getRecordTypeId();

    @TestSetup
    static void makeData(){
        List<Pre_Defined_Quote_Notes__c> predefinedNotes = new List<Pre_Defined_Quote_Notes__c>();
        Pre_Defined_Quote_Notes__c techNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'TECH SUPPORT',
            NoteDetails__c = 'Technical Notes'
        );
        predefinedNotes.add(techNotes);
        Pre_defined_Quote_Notes__c equipmentNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'EQUIPMENT QUOTED STATEMENT',
            NoteDetails__c = 'Equipment Notes'
        );
        predefinedNotes.add(equipmentNotes);
        insert predefinedNotes;
        Account account = TestDataFactory.createFundamentalTestAccount();
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            RecordTypeId = quoteFundamentalRecTypeId,
            SBQQ__Account__c = account.Id,
            SBQQ__Notes__c = 'Initial notes for the quote \r\nwith multiple lines'
        );
        insert quote;

    }

    @isTest
    static void testConstructor() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();
        System.runAs(adminUser) {
            SBQQ__QuoteTemplate__c template = TestDataFactory.createFundamentalQuoteTemplate();
            SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

            Test.setCurrentPageReference(new PageReference('/apex/FundamentalQuoteTemplateHeader'));
            ApexPages.currentPage().getParameters().put('qid', quote.Id);
            ApexPages.currentPage().getParameters().put('tid', template.Id);
            
            FundamentalQuoteTemplateHeader controller = new FundamentalQuoteTemplateHeader(new ApexPages.StandardController(quote));

            System.assertNotEquals(null, controller.quoteId, 'Quote ID should not be null');
            System.assertNotEquals(null, controller.quote, 'Quote should not be null');
            System.assertNotEquals(null, controller.orderedNoteDescriptions, 'Ordered note descriptions should not be null');
            System.assertEquals(2, controller.orderedNoteDescriptions.size(), 'There should be two ordered note descriptions');
        }
    }
}