force-app/main/default/objects/Pre_Defined_Quote_Notes__c/Pre_Defined_Quote_Notes__c.object-meta.xml
<CustomObject>
    <label>Pre Defined Quote Note</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Pre Defined Quote Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Defined Quote Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TECH SUPPORT</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT QUOTED STATEMENT</fullName>
            </value>
            <value>
                <fullName>RENTAL PERIOD</fullName>
            </value>
            <value>
                <fullName>POWERLENS/AGM NOTE</fullName>
            </value>
            <value>
                <fullName>AGM INSTALLATION GUIDE NOTE</fullName>
            </value>
            <value>
                <fullName>FREIGHT QUOTES</fullName>
            </value>
            <value>
                <fullName>EFT PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/NoteDetails__c.field-meta.xml
<CustomField>
    <fullName>NoteDetails__c</fullName>
    <label>Note Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/Predefined_Qts__c.object-meta.xml
<CustomObject>
    <label>Predefined+Qts</label>
    <nameField>
        <label>Predefined+Qts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined+Qts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Predefined_Qts__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Pre_Defined_Quote_Note__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Predefined Notes (QUOTE)</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PredefinedQuoteNotesControllerTest.cls
@isTest
public with sharing class PredefinedQuoteNotesControllerTest {

    @TestSetup
    static void makeData(){
        List<Pre_Defined_Quote_Notes__c> predefinedNotes = new List<Pre_Defined_Quote_Notes__c>();
        Pre_Defined_Quote_Notes__c techNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'TECH SUPPORT',
            NoteDetails__c = 'Technical Notes'
        );
        predefinedNotes.add(techNotes);
        Pre_defined_Quote_Notes__c equipmentNotes = new Pre_Defined_Quote_Notes__c(
            Category__c = 'EQUIPMENT QUOTED STATEMENT',
            NoteDetails__c = 'Equipment Notes'
        );
        predefinedNotes.add(equipmentNotes);
        insert predefinedNotes;

        Account account = TestDataFactory.createFundamentalTestAccount();
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            RecordTypeId = TestDataFactory.quoteFundamentalRecTypeId,
            SBQQ__Account__c = account.Id
        );
        insert quote;

    }

    @isTest
    static void getQuoteNotesTest() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();

        System.runAs(adminUser) {
            SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
            List<Object> notes = PredefinedQuoteNotesController.getQuoteNotes(quote.Id);
            System.assertNotEquals(null, notes, 'Notes should not be null');
            System.assertEquals(2, notes.size(), 'There should be two notes');
        }
    }

    @isTest
    static void getAllCategoriesTest() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();

        System.runAs(adminUser) {
            List<String> categories = PredefinedQuoteNotesController.getAllCategories();
            System.assertNotEquals(null, categories, 'Categories should not be null');
            System.assertEquals(2, categories.size(), 'There should be two categories');
        }
    }

    @isTest
    static void getNotesByCategoryTest() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();

        System.runAs(adminUser) {
            List<Pre_Defined_Quote_Notes__c> notes = PredefinedQuoteNotesController.getNotesByCategory('TECH SUPPORT');
            System.assertNotEquals(null, notes, 'Notes should not be null');
            System.assertEquals(1, notes.size(), 'There should be one note in this category');
        }
    }

    @isTest
    static void saveNoteSelectionsTest() {
        User adminUser = TestDataFactory.createTestSystemAdminUser();

        System.runAs(adminUser) {
            SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
            List<Id> selectedNoteIds = new List<Id>();
            List<Pre_Defined_Quote_Notes__c> notes = [SELECT Id FROM Pre_Defined_Quote_Notes__c LIMIT 1];
            selectedNoteIds.add(notes[0].Id);

            Test.startTest();
            PredefinedQuoteNotesController.saveNoteSelections(selectedNoteIds, quote.Id);
            Test.stopTest();

            List<Predefined_Qts__c> savedNotes = [SELECT Id FROM Predefined_Qts__c WHERE Quote__c = :quote.Id];
            System.assertEquals(1, savedNotes.size(), 'One note should be saved');
        }
    }
    
}