force-app/main/default/objects/Account/fields/Fundamental_Account__c.field-meta.xml
<CustomField>
    <fullName>Fundamental_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fundamental Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Code_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code_1__c</fullName>
    <label>Tax Code 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>HST</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
            <value>
                <fullName>NTX</fullName>
                <isActive>false</isActive>
                <label>NTX</label>
            </value>
            <value>
                <fullName>QST</fullName>
                <isActive>false</isActive>
                <label>QST</label>
            </value>
            <value>
                <fullName>RST</fullName>
                <isActive>false</isActive>
                <label>RST</label>
            </value>
            <value>
                <fullName>Test 1</fullName>
                <isActive>false</isActive>
                <label>Test 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_code_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_code_2__c</fullName>
    <label>Tax Code 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GST</fullName>
            </value>
            <value>
                <fullName>HST</fullName>
            </value>
            <value>
                <fullName>PST</fullName>
            </value>
            <value>
                <fullName>NTX</fullName>
                <isActive>false</isActive>
                <label>NTX</label>
            </value>
            <value>
                <fullName>QST</fullName>
                <isActive>false</isActive>
                <label>QST</label>
            </value>
            <value>
                <fullName>RST</fullName>
                <isActive>false</isActive>
                <label>RST</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Will_Call__c.field-meta.xml
<CustomField>
    <fullName>Will_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Will Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Code_1__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code_1__c</fullName>
    <formula>TEXT(SBQQ__Account__r.Tax_Code_1__c)</formula>
    <label>Tax Code 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Tax_Code_2__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code_2__c</fullName>
    <formula>TEXT(SBQQ__Account__r.Tax_code_2__c)</formula>
    <label>Tax Code 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Will_Call__c.field-meta.xml
<CustomField>
    <fullName>Will_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Will Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Arbutus_Quotes.recordType-meta.xml
<RecordType>
    <fullName>Arbutus_Quotes</fullName>
    <active>true</active>
    <description>Arbutus Quotes</description>
    <label>Arbutus Quotes</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Fundamental_Quotes.recordType-meta.xml
<RecordType>
    <fullName>Fundamental_Quotes</fullName>
    <active>true</active>
    <description>Fundamental Quotes</description>
    <label>Fundamental Quotes</label>
</RecordType>

force-app/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arbutus West</fullName>
            </value>
            <value>
                <fullName>Fundamentals Rental</fullName>
            </value>
            <value>
                <fullName>Acasia Power</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
    public static final String quoteFundamentalRecTypeId = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Fundamental_Quotes').getRecordTypeId();
    public static final String quoteArbutusRecTypeId = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Arbutus_Quotes').getRecordTypeId();
    
    public static User createTestSystemAdminUser() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User adminUser = new User(
            ProfileId = adminProfile.Id,
            FirstName = 'Admin',
            LastName = 'User',
            Email = 'admin@arbutus.com',
            Alias = 'adTaw',
            Username = 'admin@arbutus.com',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/Los_Angeles',
            Business_Unit__c = 'Arbutus West'
        );
        insert adminUser;

        return adminUser;
    }

    public static Account createFundamentalTestAccount() {
        Account account = new Account(
            Name = 'Test Account',
            Will_Call__c = false,
            Fundamental_Account__c = true,
            Tax_Code_1__c = 'GST',
            Tax_Code_2__c = 'PST',
            BillingState = 'Ontario',
            BillingCountry = 'Canada',
            ShippingState = 'Ontario',
            ShippingCountry = 'Canada'
        );
        insert account;

        return account;
    }

    public static SBQQ__QuoteTemplate__c createFundamentalQuoteTemplate() {
        SBQQ__QuoteTemplate__c template = new SBQQ__QuoteTemplate__c(
            Name = 'Test Quote Template BOL'
        );
        insert template;

        return template;
    }

    public static SBQQ__QuoteTemplate__c createArbutusServiceLineTemplate() {
        SBQQ__QuoteTemplate__c template = new SBQQ__QuoteTemplate__c(
            Name = 'Arbutus Service Line Template'
        );
        insert template;

        return template;
    }

}