force-app/main/default/objects/Fundamenta_Predefined_Notes__mdt/Fundamenta_Predefined_Notes__mdt.object-meta.xml
<CustomObject>
    <description>Tech support and Equipment categories automatically added to every fundamental quote</description>
    <label>Fundamenta Predefined Note</label>
    <pluralLabel>Fundamenta Predefined Notes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/Pre_Defined_Quote_Notes__c.object-meta.xml
<CustomObject>
    <label>Pre Defined Quote Note</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Pre Defined Quote Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre Defined Quote Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pre_Defined_Quote_Notes__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TECH SUPPORT</fullName>
            </value>
            <value>
                <fullName>EQUIPMENT QUOTED STATEMENT</fullName>
            </value>
            <value>
                <fullName>RENTAL PERIOD</fullName>
            </value>
            <value>
                <fullName>POWERLENS/AGM NOTE</fullName>
            </value>
            <value>
                <fullName>AGM INSTALLATION GUIDE NOTE</fullName>
            </value>
            <value>
                <fullName>FREIGHT QUOTES</fullName>
            </value>
            <value>
                <fullName>EFT PAYMENTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/Predefined_Qts__c.object-meta.xml
<CustomObject>
    <label>Predefined+Qts</label>
    <nameField>
        <label>Predefined+Qts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Predefined+Qts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Predefined_Qts__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Pre_Defined_Quote_Note__r.Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Pre_Defined_Quote_Note__c.field-meta.xml
<CustomField>
    <fullName>Pre_Defined_Quote_Note__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Pre Defined Quote Note</label>
    <referenceTo>Pre_Defined_Quote_Notes__c</referenceTo>
    <relationshipLabel>Predefined+Qts</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Predefined_Qts__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Predefined Notes (QUOTE)</relationshipLabel>
    <relationshipName>Predefined_Qts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Fundamental_Quotes.recordType-meta.xml
<RecordType>
    <fullName>Fundamental_Quotes</fullName>
    <active>true</active>
    <description>Fundamental Quotes</description>
    <label>Fundamental Quotes</label>
</RecordType>

force-app/main/default/classes/QuoteTriggerHandler.cls
public without sharing class QuoteTriggerHandler {
	private static final String fundamentalRecTypeId = Schema.getGlobalDescribe().get('SBQQ__Quote__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Fundamental_Quotes').getRecordTypeId();

    private static  List<Fundamenta_Predefined_Notes__mdt> predefinedNotesCategory = Fundamenta_Predefined_Notes__mdt.getAll().values();

    public static void onAfterInsert(Map<Id,SBQQ__Quote__c> newQuotes) {
        insertNotes(newQuotes);
        
    }
    private static void insertNotes(Map<Id,SBQQ__Quote__c> newQuotes){
        List<Predefined_Qts__c> predefinedNotesForInsert = new List<Predefined_Qts__c>();
        List<String> notesCategories = new List<String>();

        for(Fundamenta_Predefined_Notes__mdt mdtNote : predefinedNotesCategory) {
            notesCategories.add(mdtNote.Label);
        }

        Map<Id,Pre_Defined_Quote_Notes__c> predefinedNotes = new Map<Id, Pre_Defined_Quote_Notes__c>([SELECT Id, Category__c 
                                                        FROM Pre_Defined_Quote_Notes__c  
                                                        WHERE Category__c IN :notesCategories]);
    
        for(SBQQ__Quote__c quote : newQuotes.values()) {
            if(quote.RecordTypeId != fundamentalRecTypeId){ continue; }
            
            predefinedNotesForInsert.addAll(createNotes(quote.Id, predefinedNotes.keySet()));
            
        }

        if(!predefinedNotesForInsert.isEmpty()){
            try {
                insert predefinedNotesForInsert;
            } catch (DmlException e) {
                System.debug('Error inserting predefined notes: ' + e.getMessage());
            }
        }
    }

    public static List<Predefined_Qts__c> createNotes(Id quoteId, Set<Id> notesId){
        List<Predefined_Qts__c> predefinedNotes = new List<Predefined_Qts__c>();
        for(Id noteId : notesId){
            Predefined_Qts__c predefinedNote = new Predefined_Qts__c();
            predefinedNote.Quote__c = quoteId;
            predefinedNote.Pre_Defined_Quote_Note__c = noteId;
            predefinedNotes.add(predefinedNote);
        }
        return predefinedNotes;
    }

}